# Generated by Django 5.2.7 on 2025-10-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='resource',
            field=models.TextField(default='https://medium.com/@karimmirzaguliyev/unleashing-the-power-of-django-orm-a-comprehensive-guide-b00aa9b99dd0'),
            preserve_default=False,
        ),
    ]
