# Generated by Django 5.2.7 on 2025-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create_date'),
        ),
    ]
