# Generated by Django 5.2.3 on 2025-10-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='poster',
            field=models.ImageField(default='default.png', upload_to='announcements/posters'),
        ),
        migrations.CreateModel(
            name='AnnouncementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='announcements/images/')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='announcements.announcement')),
            ],
        ),
    ]
