# Generated by Django 5.2.3 on 2025-10-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_сreator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='сreator',
            new_name='creator',
        ),
    ]
