# Generated by Django 5.2.3 on 2025-10-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_text_alter_announcement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/reactions/')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
